# Documentation for the sass-lint Linters is available at:
# https://github.com/sasstools/sass-lint/tree/master/docs/rules

options:
  formatter: stylish
  merge-default-rules: true
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations:
    - 1
    - exclude:
      - 'breakpoint'
      - 'mq'
      - 'respond-to'
      - 'rtl'
      - 'clearfix'

  # Line Spacing
  one-declaration-per-line: 0
  empty-line-between-blocks:
    - 0
    - ignore-single-line-rulesets: true
  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 2
  no-color-literals: 0
  # no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties:
      - '*font-family'
      - '*height'
      - 'interpolation-mode'
      - '*margin-left'
      - '*vertical-align'
      - '*width'
  no-qualifying-elements: 0
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes: 1
  no-warn: 2
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 1
    - convention: hyphenatedbem
  function-name-format: 2
  id-name-format: 2
  mixin-name-format:
    - 2
    - convention: hyphenatedbem
  placeholder-name-format:
    - 2
    - convention: hyphenatedbem
  variable-name-format: 2

  # Style Guide
  bem-depth: 0
  border-zero: 2
  brace-style:
    - 2
    - style: stroustrup
    - allow-single-line: false
  clean-import-paths: 2
  empty-args: 0
  hex-length: 2
  hex-notation: 0
  # indentation: 2
  leading-zero: 2
  nesting-depth:
    - 2
    - max-depth: 6
  property-sort-order: 0
  quotes: 0
  shorthand-values: 2
  url-quotes: 0
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 0
  space-before-colon: 0
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 0
  space-between-parens: 0
  space-around-operator: 0

  # Final Items
  trailing-semicolon: 1
  final-newline: 0
  no-trailing-whitespace: 0
